//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 이 소스 코드가 Microsoft.VSDesigner, 버전 4.0.30319.42000에서 자동으로 생성되었습니다.
// 
#pragma warning disable 1591

namespace MES_APP_P90.wsPP4G303FL {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PP4G303FLSoap", Namespace="http://www.Bizentro.com/")]
    public partial class PP4G303FL : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback cPIssCmpsManually_P_ISSUE_COMPONENTS_MANUALLYOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PP4G303FL() {
            this.Url = global::MES_APP_P90.Properties.Settings.Default.MES_APP_P80_wsPP4G303FL_PP4G303FL;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event cPIssCmpsManually_P_ISSUE_COMPONENTS_MANUALLYCompletedEventHandler cPIssCmpsManually_P_ISSUE_COMPONENTS_MANUALLYCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Bizentro.com/cPIssCmpsManually_P_ISSUE_COMPONENTS_MANUALLY", RequestNamespace="http://www.Bizentro.com/", ResponseNamespace="http://www.Bizentro.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void cPIssCmpsManually_P_ISSUE_COMPONENTS_MANUALLY(string[] pvStrGlobalCollection, DsPIssueComponentsManually dataSet) {
            this.Invoke("cPIssCmpsManually_P_ISSUE_COMPONENTS_MANUALLY", new object[] {
                        pvStrGlobalCollection,
                        dataSet});
        }
        
        /// <remarks/>
        public void cPIssCmpsManually_P_ISSUE_COMPONENTS_MANUALLYAsync(string[] pvStrGlobalCollection, DsPIssueComponentsManually dataSet) {
            this.cPIssCmpsManually_P_ISSUE_COMPONENTS_MANUALLYAsync(pvStrGlobalCollection, dataSet, null);
        }
        
        /// <remarks/>
        public void cPIssCmpsManually_P_ISSUE_COMPONENTS_MANUALLYAsync(string[] pvStrGlobalCollection, DsPIssueComponentsManually dataSet, object userState) {
            if ((this.cPIssCmpsManually_P_ISSUE_COMPONENTS_MANUALLYOperationCompleted == null)) {
                this.cPIssCmpsManually_P_ISSUE_COMPONENTS_MANUALLYOperationCompleted = new System.Threading.SendOrPostCallback(this.OncPIssCmpsManually_P_ISSUE_COMPONENTS_MANUALLYOperationCompleted);
            }
            this.InvokeAsync("cPIssCmpsManually_P_ISSUE_COMPONENTS_MANUALLY", new object[] {
                        pvStrGlobalCollection,
                        dataSet}, this.cPIssCmpsManually_P_ISSUE_COMPONENTS_MANUALLYOperationCompleted, userState);
        }
        
        private void OncPIssCmpsManually_P_ISSUE_COMPONENTS_MANUALLYOperationCompleted(object arg) {
            if ((this.cPIssCmpsManually_P_ISSUE_COMPONENTS_MANUALLYCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cPIssCmpsManually_P_ISSUE_COMPONENTS_MANUALLYCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    // 이 유형 정의는 System.Data.Design.TypedDataSetSchemaImporterExtension 스키마 가져오기 확장에 의해 생성되었습니다.
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("DsPIssueComponentsManually")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    public partial class DsPIssueComponentsManually : global::System.Data.DataSet {
        
        private I_I_GOODS_MVMTDataTable tableI_I_GOODS_MVMT;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public DsPIssueComponentsManually() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected DsPIssueComponentsManually(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["I_I_GOODS_MVMT"] != null)) {
                    base.Tables.Add(new I_I_GOODS_MVMTDataTable(ds.Tables["I_I_GOODS_MVMT"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public I_I_GOODS_MVMTDataTable I_I_GOODS_MVMT {
            get {
                return this.tableI_I_GOODS_MVMT;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            DsPIssueComponentsManually cln = ((DsPIssueComponentsManually)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["I_I_GOODS_MVMT"] != null)) {
                    base.Tables.Add(new I_I_GOODS_MVMTDataTable(ds.Tables["I_I_GOODS_MVMT"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableI_I_GOODS_MVMT = ((I_I_GOODS_MVMTDataTable)(base.Tables["I_I_GOODS_MVMT"]));
            if ((initTable == true)) {
                if ((this.tableI_I_GOODS_MVMT != null)) {
                    this.tableI_I_GOODS_MVMT.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private void InitClass() {
            this.DataSetName = "DsPIssueComponentsManually";
            this.Prefix = "";
            this.Namespace = "http://bizentro.com/DsPIssueComponentsManually.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableI_I_GOODS_MVMT = new I_I_GOODS_MVMTDataTable();
            base.Tables.Add(this.tableI_I_GOODS_MVMT);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private bool ShouldSerializeI_I_GOODS_MVMT() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            DsPIssueComponentsManually ds = new DsPIssueComponentsManually();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public delegate void I_I_GOODS_MVMTRowChangeEventHandler(object sender, I_I_GOODS_MVMTRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class I_I_GOODS_MVMTDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnplant_cd;
            
            private global::System.Data.DataColumn columnprodt_order_no;
            
            private global::System.Data.DataColumn columnopr_no;
            
            private global::System.Data.DataColumn columnreport_dt;
            
            private global::System.Data.DataColumn columnitem_cd;
            
            private global::System.Data.DataColumn columnsl_cd;
            
            private global::System.Data.DataColumn columntracking_no;
            
            private global::System.Data.DataColumn columnlot_no;
            
            private global::System.Data.DataColumn columnlot_sub_no;
            
            private global::System.Data.DataColumn columnentry_qty;
            
            private global::System.Data.DataColumn columnentry_unit;
            
            private global::System.Data.DataColumn columnwc_cd;
            
            private global::System.Data.DataColumn columnseq;
            
            private global::System.Data.DataColumn columnreq_no;
            
            private global::System.Data.DataColumn columnitem_document_no;
            
            private global::System.Data.DataColumn columntrns_type;
            
            private global::System.Data.DataColumn columnmov_type;
            
            private global::System.Data.DataColumn columnrow_count;
            
            private global::System.Data.DataColumn columnmv_req_no;
            
            private global::System.Data.DataColumn columnmv_req_seq;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public I_I_GOODS_MVMTDataTable() {
                this.TableName = "I_I_GOODS_MVMT";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal I_I_GOODS_MVMTDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected I_I_GOODS_MVMTDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn plant_cdColumn {
                get {
                    return this.columnplant_cd;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn prodt_order_noColumn {
                get {
                    return this.columnprodt_order_no;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn opr_noColumn {
                get {
                    return this.columnopr_no;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn report_dtColumn {
                get {
                    return this.columnreport_dt;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn item_cdColumn {
                get {
                    return this.columnitem_cd;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn sl_cdColumn {
                get {
                    return this.columnsl_cd;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn tracking_noColumn {
                get {
                    return this.columntracking_no;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn lot_noColumn {
                get {
                    return this.columnlot_no;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn lot_sub_noColumn {
                get {
                    return this.columnlot_sub_no;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn entry_qtyColumn {
                get {
                    return this.columnentry_qty;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn entry_unitColumn {
                get {
                    return this.columnentry_unit;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn wc_cdColumn {
                get {
                    return this.columnwc_cd;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn seqColumn {
                get {
                    return this.columnseq;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn req_noColumn {
                get {
                    return this.columnreq_no;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn item_document_noColumn {
                get {
                    return this.columnitem_document_no;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn trns_typeColumn {
                get {
                    return this.columntrns_type;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn mov_typeColumn {
                get {
                    return this.columnmov_type;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn row_countColumn {
                get {
                    return this.columnrow_count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn mv_req_noColumn {
                get {
                    return this.columnmv_req_no;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn mv_req_seqColumn {
                get {
                    return this.columnmv_req_seq;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public I_I_GOODS_MVMTRow this[int index] {
                get {
                    return ((I_I_GOODS_MVMTRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event I_I_GOODS_MVMTRowChangeEventHandler I_I_GOODS_MVMTRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event I_I_GOODS_MVMTRowChangeEventHandler I_I_GOODS_MVMTRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event I_I_GOODS_MVMTRowChangeEventHandler I_I_GOODS_MVMTRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event I_I_GOODS_MVMTRowChangeEventHandler I_I_GOODS_MVMTRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void AddI_I_GOODS_MVMTRow(I_I_GOODS_MVMTRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public I_I_GOODS_MVMTRow AddI_I_GOODS_MVMTRow(
                        string plant_cd, 
                        string prodt_order_no, 
                        string opr_no, 
                        System.DateTime report_dt, 
                        string item_cd, 
                        string sl_cd, 
                        string tracking_no, 
                        string lot_no, 
                        int lot_sub_no, 
                        decimal entry_qty, 
                        string entry_unit, 
                        string wc_cd, 
                        int seq, 
                        string req_no, 
                        string item_document_no, 
                        string trns_type, 
                        string mov_type, 
                        int row_count, 
                        string mv_req_no, 
                        decimal mv_req_seq) {
                I_I_GOODS_MVMTRow rowI_I_GOODS_MVMTRow = ((I_I_GOODS_MVMTRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        plant_cd,
                        prodt_order_no,
                        opr_no,
                        report_dt,
                        item_cd,
                        sl_cd,
                        tracking_no,
                        lot_no,
                        lot_sub_no,
                        entry_qty,
                        entry_unit,
                        wc_cd,
                        seq,
                        req_no,
                        item_document_no,
                        trns_type,
                        mov_type,
                        row_count,
                        mv_req_no,
                        mv_req_seq};
                rowI_I_GOODS_MVMTRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowI_I_GOODS_MVMTRow);
                return rowI_I_GOODS_MVMTRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                I_I_GOODS_MVMTDataTable cln = ((I_I_GOODS_MVMTDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new I_I_GOODS_MVMTDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal void InitVars() {
                this.columnplant_cd = base.Columns["plant_cd"];
                this.columnprodt_order_no = base.Columns["prodt_order_no"];
                this.columnopr_no = base.Columns["opr_no"];
                this.columnreport_dt = base.Columns["report_dt"];
                this.columnitem_cd = base.Columns["item_cd"];
                this.columnsl_cd = base.Columns["sl_cd"];
                this.columntracking_no = base.Columns["tracking_no"];
                this.columnlot_no = base.Columns["lot_no"];
                this.columnlot_sub_no = base.Columns["lot_sub_no"];
                this.columnentry_qty = base.Columns["entry_qty"];
                this.columnentry_unit = base.Columns["entry_unit"];
                this.columnwc_cd = base.Columns["wc_cd"];
                this.columnseq = base.Columns["seq"];
                this.columnreq_no = base.Columns["req_no"];
                this.columnitem_document_no = base.Columns["item_document_no"];
                this.columntrns_type = base.Columns["trns_type"];
                this.columnmov_type = base.Columns["mov_type"];
                this.columnrow_count = base.Columns["row_count"];
                this.columnmv_req_no = base.Columns["mv_req_no"];
                this.columnmv_req_seq = base.Columns["mv_req_seq"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            private void InitClass() {
                this.columnplant_cd = new global::System.Data.DataColumn("plant_cd", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnplant_cd);
                this.columnprodt_order_no = new global::System.Data.DataColumn("prodt_order_no", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnprodt_order_no);
                this.columnopr_no = new global::System.Data.DataColumn("opr_no", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnopr_no);
                this.columnreport_dt = new global::System.Data.DataColumn("report_dt", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnreport_dt);
                this.columnitem_cd = new global::System.Data.DataColumn("item_cd", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnitem_cd);
                this.columnsl_cd = new global::System.Data.DataColumn("sl_cd", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsl_cd);
                this.columntracking_no = new global::System.Data.DataColumn("tracking_no", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntracking_no);
                this.columnlot_no = new global::System.Data.DataColumn("lot_no", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnlot_no);
                this.columnlot_sub_no = new global::System.Data.DataColumn("lot_sub_no", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnlot_sub_no);
                this.columnentry_qty = new global::System.Data.DataColumn("entry_qty", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnentry_qty);
                this.columnentry_unit = new global::System.Data.DataColumn("entry_unit", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnentry_unit);
                this.columnwc_cd = new global::System.Data.DataColumn("wc_cd", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnwc_cd);
                this.columnseq = new global::System.Data.DataColumn("seq", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnseq);
                this.columnreq_no = new global::System.Data.DataColumn("req_no", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnreq_no);
                this.columnitem_document_no = new global::System.Data.DataColumn("item_document_no", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnitem_document_no);
                this.columntrns_type = new global::System.Data.DataColumn("trns_type", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntrns_type);
                this.columnmov_type = new global::System.Data.DataColumn("mov_type", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmov_type);
                this.columnrow_count = new global::System.Data.DataColumn("row_count", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnrow_count);
                this.columnmv_req_no = new global::System.Data.DataColumn("mv_req_no", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmv_req_no);
                this.columnmv_req_seq = new global::System.Data.DataColumn("mv_req_seq", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmv_req_seq);
                this.columnplant_cd.DefaultValue = ((string)(""));
                this.columnprodt_order_no.DefaultValue = ((string)(""));
                this.columnopr_no.DefaultValue = ((string)(""));
                this.columnreport_dt.DateTimeMode = global::System.Data.DataSetDateTime.Unspecified;
                this.columnitem_cd.DefaultValue = ((string)(""));
                this.columnsl_cd.DefaultValue = ((string)(""));
                this.columnlot_no.DefaultValue = ((string)(""));
                this.columnlot_sub_no.DefaultValue = ((int)(0));
                this.columnentry_qty.DefaultValue = ((decimal)(0m));
                this.columnentry_unit.DefaultValue = ((string)(""));
                this.columnwc_cd.DefaultValue = ((string)(""));
                this.columnseq.DefaultValue = ((int)(0));
                this.columnreq_no.DefaultValue = ((string)(""));
                this.columnitem_document_no.DefaultValue = ((string)(""));
                this.columntrns_type.DefaultValue = ((string)(""));
                this.columnmov_type.DefaultValue = ((string)(""));
                this.columnrow_count.DefaultValue = ((int)(0));
                this.columnmv_req_no.DefaultValue = ((string)(""));
                this.columnmv_req_seq.DefaultValue = ((decimal)(0m));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public I_I_GOODS_MVMTRow NewI_I_GOODS_MVMTRow() {
                return ((I_I_GOODS_MVMTRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new I_I_GOODS_MVMTRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(I_I_GOODS_MVMTRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.I_I_GOODS_MVMTRowChanged != null)) {
                    this.I_I_GOODS_MVMTRowChanged(this, new I_I_GOODS_MVMTRowChangeEvent(((I_I_GOODS_MVMTRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.I_I_GOODS_MVMTRowChanging != null)) {
                    this.I_I_GOODS_MVMTRowChanging(this, new I_I_GOODS_MVMTRowChangeEvent(((I_I_GOODS_MVMTRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.I_I_GOODS_MVMTRowDeleted != null)) {
                    this.I_I_GOODS_MVMTRowDeleted(this, new I_I_GOODS_MVMTRowChangeEvent(((I_I_GOODS_MVMTRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.I_I_GOODS_MVMTRowDeleting != null)) {
                    this.I_I_GOODS_MVMTRowDeleting(this, new I_I_GOODS_MVMTRowChangeEvent(((I_I_GOODS_MVMTRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void RemoveI_I_GOODS_MVMTRow(I_I_GOODS_MVMTRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DsPIssueComponentsManually ds = new DsPIssueComponentsManually();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "I_I_GOODS_MVMTDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class I_I_GOODS_MVMTRow : global::System.Data.DataRow {
            
            private I_I_GOODS_MVMTDataTable tableI_I_GOODS_MVMT;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal I_I_GOODS_MVMTRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableI_I_GOODS_MVMT = ((I_I_GOODS_MVMTDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string plant_cd {
                get {
                    try {
                        return ((string)(this[this.tableI_I_GOODS_MVMT.plant_cdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'I_I_GOODS_MVMT\' 테이블의 \'plant_cd\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableI_I_GOODS_MVMT.plant_cdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string prodt_order_no {
                get {
                    try {
                        return ((string)(this[this.tableI_I_GOODS_MVMT.prodt_order_noColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'I_I_GOODS_MVMT\' 테이블의 \'prodt_order_no\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableI_I_GOODS_MVMT.prodt_order_noColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string opr_no {
                get {
                    try {
                        return ((string)(this[this.tableI_I_GOODS_MVMT.opr_noColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'I_I_GOODS_MVMT\' 테이블의 \'opr_no\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableI_I_GOODS_MVMT.opr_noColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public System.DateTime report_dt {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableI_I_GOODS_MVMT.report_dtColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'I_I_GOODS_MVMT\' 테이블의 \'report_dt\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableI_I_GOODS_MVMT.report_dtColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string item_cd {
                get {
                    try {
                        return ((string)(this[this.tableI_I_GOODS_MVMT.item_cdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'I_I_GOODS_MVMT\' 테이블의 \'item_cd\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableI_I_GOODS_MVMT.item_cdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string sl_cd {
                get {
                    try {
                        return ((string)(this[this.tableI_I_GOODS_MVMT.sl_cdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'I_I_GOODS_MVMT\' 테이블의 \'sl_cd\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableI_I_GOODS_MVMT.sl_cdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string tracking_no {
                get {
                    try {
                        return ((string)(this[this.tableI_I_GOODS_MVMT.tracking_noColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'I_I_GOODS_MVMT\' 테이블의 \'tracking_no\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableI_I_GOODS_MVMT.tracking_noColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string lot_no {
                get {
                    try {
                        return ((string)(this[this.tableI_I_GOODS_MVMT.lot_noColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'I_I_GOODS_MVMT\' 테이블의 \'lot_no\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableI_I_GOODS_MVMT.lot_noColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public int lot_sub_no {
                get {
                    try {
                        return ((int)(this[this.tableI_I_GOODS_MVMT.lot_sub_noColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'I_I_GOODS_MVMT\' 테이블의 \'lot_sub_no\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableI_I_GOODS_MVMT.lot_sub_noColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public decimal entry_qty {
                get {
                    try {
                        return ((decimal)(this[this.tableI_I_GOODS_MVMT.entry_qtyColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'I_I_GOODS_MVMT\' 테이블의 \'entry_qty\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableI_I_GOODS_MVMT.entry_qtyColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string entry_unit {
                get {
                    try {
                        return ((string)(this[this.tableI_I_GOODS_MVMT.entry_unitColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'I_I_GOODS_MVMT\' 테이블의 \'entry_unit\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableI_I_GOODS_MVMT.entry_unitColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string wc_cd {
                get {
                    try {
                        return ((string)(this[this.tableI_I_GOODS_MVMT.wc_cdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'I_I_GOODS_MVMT\' 테이블의 \'wc_cd\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableI_I_GOODS_MVMT.wc_cdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public int seq {
                get {
                    try {
                        return ((int)(this[this.tableI_I_GOODS_MVMT.seqColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'I_I_GOODS_MVMT\' 테이블의 \'seq\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableI_I_GOODS_MVMT.seqColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string req_no {
                get {
                    try {
                        return ((string)(this[this.tableI_I_GOODS_MVMT.req_noColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'I_I_GOODS_MVMT\' 테이블의 \'req_no\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableI_I_GOODS_MVMT.req_noColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string item_document_no {
                get {
                    try {
                        return ((string)(this[this.tableI_I_GOODS_MVMT.item_document_noColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'I_I_GOODS_MVMT\' 테이블의 \'item_document_no\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableI_I_GOODS_MVMT.item_document_noColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string trns_type {
                get {
                    try {
                        return ((string)(this[this.tableI_I_GOODS_MVMT.trns_typeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'I_I_GOODS_MVMT\' 테이블의 \'trns_type\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableI_I_GOODS_MVMT.trns_typeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string mov_type {
                get {
                    try {
                        return ((string)(this[this.tableI_I_GOODS_MVMT.mov_typeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'I_I_GOODS_MVMT\' 테이블의 \'mov_type\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableI_I_GOODS_MVMT.mov_typeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public int row_count {
                get {
                    try {
                        return ((int)(this[this.tableI_I_GOODS_MVMT.row_countColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'I_I_GOODS_MVMT\' 테이블의 \'row_count\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableI_I_GOODS_MVMT.row_countColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string mv_req_no {
                get {
                    try {
                        return ((string)(this[this.tableI_I_GOODS_MVMT.mv_req_noColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'I_I_GOODS_MVMT\' 테이블의 \'mv_req_no\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableI_I_GOODS_MVMT.mv_req_noColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public decimal mv_req_seq {
                get {
                    try {
                        return ((decimal)(this[this.tableI_I_GOODS_MVMT.mv_req_seqColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'I_I_GOODS_MVMT\' 테이블의 \'mv_req_seq\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableI_I_GOODS_MVMT.mv_req_seqColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isplant_cdNull() {
                return this.IsNull(this.tableI_I_GOODS_MVMT.plant_cdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setplant_cdNull() {
                this[this.tableI_I_GOODS_MVMT.plant_cdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isprodt_order_noNull() {
                return this.IsNull(this.tableI_I_GOODS_MVMT.prodt_order_noColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setprodt_order_noNull() {
                this[this.tableI_I_GOODS_MVMT.prodt_order_noColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isopr_noNull() {
                return this.IsNull(this.tableI_I_GOODS_MVMT.opr_noColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setopr_noNull() {
                this[this.tableI_I_GOODS_MVMT.opr_noColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isreport_dtNull() {
                return this.IsNull(this.tableI_I_GOODS_MVMT.report_dtColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setreport_dtNull() {
                this[this.tableI_I_GOODS_MVMT.report_dtColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isitem_cdNull() {
                return this.IsNull(this.tableI_I_GOODS_MVMT.item_cdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setitem_cdNull() {
                this[this.tableI_I_GOODS_MVMT.item_cdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Issl_cdNull() {
                return this.IsNull(this.tableI_I_GOODS_MVMT.sl_cdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setsl_cdNull() {
                this[this.tableI_I_GOODS_MVMT.sl_cdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Istracking_noNull() {
                return this.IsNull(this.tableI_I_GOODS_MVMT.tracking_noColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Settracking_noNull() {
                this[this.tableI_I_GOODS_MVMT.tracking_noColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Islot_noNull() {
                return this.IsNull(this.tableI_I_GOODS_MVMT.lot_noColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setlot_noNull() {
                this[this.tableI_I_GOODS_MVMT.lot_noColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Islot_sub_noNull() {
                return this.IsNull(this.tableI_I_GOODS_MVMT.lot_sub_noColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setlot_sub_noNull() {
                this[this.tableI_I_GOODS_MVMT.lot_sub_noColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isentry_qtyNull() {
                return this.IsNull(this.tableI_I_GOODS_MVMT.entry_qtyColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setentry_qtyNull() {
                this[this.tableI_I_GOODS_MVMT.entry_qtyColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isentry_unitNull() {
                return this.IsNull(this.tableI_I_GOODS_MVMT.entry_unitColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setentry_unitNull() {
                this[this.tableI_I_GOODS_MVMT.entry_unitColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Iswc_cdNull() {
                return this.IsNull(this.tableI_I_GOODS_MVMT.wc_cdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setwc_cdNull() {
                this[this.tableI_I_GOODS_MVMT.wc_cdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsseqNull() {
                return this.IsNull(this.tableI_I_GOODS_MVMT.seqColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetseqNull() {
                this[this.tableI_I_GOODS_MVMT.seqColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isreq_noNull() {
                return this.IsNull(this.tableI_I_GOODS_MVMT.req_noColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setreq_noNull() {
                this[this.tableI_I_GOODS_MVMT.req_noColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isitem_document_noNull() {
                return this.IsNull(this.tableI_I_GOODS_MVMT.item_document_noColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setitem_document_noNull() {
                this[this.tableI_I_GOODS_MVMT.item_document_noColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Istrns_typeNull() {
                return this.IsNull(this.tableI_I_GOODS_MVMT.trns_typeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Settrns_typeNull() {
                this[this.tableI_I_GOODS_MVMT.trns_typeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Ismov_typeNull() {
                return this.IsNull(this.tableI_I_GOODS_MVMT.mov_typeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setmov_typeNull() {
                this[this.tableI_I_GOODS_MVMT.mov_typeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isrow_countNull() {
                return this.IsNull(this.tableI_I_GOODS_MVMT.row_countColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setrow_countNull() {
                this[this.tableI_I_GOODS_MVMT.row_countColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Ismv_req_noNull() {
                return this.IsNull(this.tableI_I_GOODS_MVMT.mv_req_noColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setmv_req_noNull() {
                this[this.tableI_I_GOODS_MVMT.mv_req_noColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Ismv_req_seqNull() {
                return this.IsNull(this.tableI_I_GOODS_MVMT.mv_req_seqColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setmv_req_seqNull() {
                this[this.tableI_I_GOODS_MVMT.mv_req_seqColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public class I_I_GOODS_MVMTRowChangeEvent : global::System.EventArgs {
            
            private I_I_GOODS_MVMTRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public I_I_GOODS_MVMTRowChangeEvent(I_I_GOODS_MVMTRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public I_I_GOODS_MVMTRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void cPIssCmpsManually_P_ISSUE_COMPONENTS_MANUALLYCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591