//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES_APP_P90.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://125.135.140.21/CKOET00053_Default/Services/PP/PP4G653FL.asmx")]
        public string MES_APP_Q10_wsPP4G653FL_PP4G653FL {
            get {
                return ((string)(this["MES_APP_Q10_wsPP4G653FL_PP4G653FL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://125.135.140.21/CKOET00053_Default/Services/PP/PP4G409FL.asmx")]
        public string MES_APP_Q10_wsPP4G409FL_PP4G409FL {
            get {
                return ((string)(this["MES_APP_Q10_wsPP4G409FL_PP4G409FL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://125.135.140.21/CKOET00053_Default/Services/PP/PP4G702FL.asmx")]
        public string MES_APP_Q10_wsPP4G702FL_PP4G702FL {
            get {
                return ((string)(this["MES_APP_Q10_wsPP4G702FL_PP4G702FL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://125.135.140.21/CKOET00053_Default/Services/PP/PP4G452FL.asmx")]
        public string MES_APP_Q10_wsPP4G452FL_PP4G452FL {
            get {
                return ((string)(this["MES_APP_Q10_wsPP4G452FL_PP4G452FL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://125.135.140.14/CKOET00053_Default/Services/QM/PQIG280FL.asmx")]
        public string MES_APP_Q10_wsPQIG280FL_PQIG280FL {
            get {
                return ((string)(this["MES_APP_Q10_wsPQIG280FL_PQIG280FL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://125.135.140.14/CKOET00053_Default/Services/QM/PQIG310FL.asmx")]
        public string MES_APP_Q10_wsPQIG310FL_PQIG310FL {
            get {
                return ((string)(this["MES_APP_Q10_wsPQIG310FL_PQIG310FL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://125.135.140.14/CKOET00053_Default/Services/PP/PP4G303FL.asmx")]
        public string MES_APP_P80_wsPP4G303FL_PP4G303FL {
            get {
                return ((string)(this["MES_APP_P80_wsPP4G303FL_PP4G303FL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://125.135.140.14/CKOET00053_Default/Services/PP/PP4G702FL.asmx")]
        public string MES_APP_P80_wsPP4G702FL_PP4G702FL {
            get {
                return ((string)(this["MES_APP_P80_wsPP4G702FL_PP4G702FL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://125.135.140.14/CKOET00053_Default/Services/PP/PP4G653FL.asmx")]
        public string MES_APP_P80_wsPP4G653FL_PP4G653FL {
            get {
                return ((string)(this["MES_APP_P80_wsPP4G653FL_PP4G653FL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://125.135.140.14/CKOET00053_Default/Services/PP/PP4G409FL.asmx")]
        public string MES_APP_P80_wsPP4G409FL_PP4G409FL {
            get {
                return ((string)(this["MES_APP_P80_wsPP4G409FL_PP4G409FL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://125.135.140.21/CKOET00053_Default/Services/PP/PP4G452FL.asmx")]
        public string MES_APP_P80_wsPP4G452FL_PP4G452FL {
            get {
                return ((string)(this["MES_APP_P80_wsPP4G452FL_PP4G452FL"]));
            }
        }
    }
}
