//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 이 소스 코드가 Microsoft.VSDesigner, 버전 4.0.30319.42000에서 자동으로 생성되었습니다.
// 
#pragma warning disable 1591

namespace MES_APP_P90.wsPP4G409FL {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PP4G409FLSoap", Namespace="http://www.Bizentro.com/")]
    public partial class PP4G409FL : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback cPCnclCnfmRsltByOp_P_CNCL_CNFM_RSLT_BY_OPR_SVROperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PP4G409FL() {
            this.Url = global::MES_APP_P90.Properties.Settings.Default.MES_APP_P80_wsPP4G409FL_PP4G409FL;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event cPCnclCnfmRsltByOp_P_CNCL_CNFM_RSLT_BY_OPR_SVRCompletedEventHandler cPCnclCnfmRsltByOp_P_CNCL_CNFM_RSLT_BY_OPR_SVRCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Bizentro.com/cPCnclCnfmRsltByOp_P_CNCL_CNFM_RSLT_BY_OPR_SVR", RequestNamespace="http://www.Bizentro.com/", ResponseNamespace="http://www.Bizentro.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void cPCnclCnfmRsltByOp_P_CNCL_CNFM_RSLT_BY_OPR_SVR(string[] pvStrGlobalCollection, string I1_b_plant_plant_cd, DsPCnclCnfmRsltByOprSvr dataSet) {
            this.Invoke("cPCnclCnfmRsltByOp_P_CNCL_CNFM_RSLT_BY_OPR_SVR", new object[] {
                        pvStrGlobalCollection,
                        I1_b_plant_plant_cd,
                        dataSet});
        }
        
        /// <remarks/>
        public void cPCnclCnfmRsltByOp_P_CNCL_CNFM_RSLT_BY_OPR_SVRAsync(string[] pvStrGlobalCollection, string I1_b_plant_plant_cd, DsPCnclCnfmRsltByOprSvr dataSet) {
            this.cPCnclCnfmRsltByOp_P_CNCL_CNFM_RSLT_BY_OPR_SVRAsync(pvStrGlobalCollection, I1_b_plant_plant_cd, dataSet, null);
        }
        
        /// <remarks/>
        public void cPCnclCnfmRsltByOp_P_CNCL_CNFM_RSLT_BY_OPR_SVRAsync(string[] pvStrGlobalCollection, string I1_b_plant_plant_cd, DsPCnclCnfmRsltByOprSvr dataSet, object userState) {
            if ((this.cPCnclCnfmRsltByOp_P_CNCL_CNFM_RSLT_BY_OPR_SVROperationCompleted == null)) {
                this.cPCnclCnfmRsltByOp_P_CNCL_CNFM_RSLT_BY_OPR_SVROperationCompleted = new System.Threading.SendOrPostCallback(this.OncPCnclCnfmRsltByOp_P_CNCL_CNFM_RSLT_BY_OPR_SVROperationCompleted);
            }
            this.InvokeAsync("cPCnclCnfmRsltByOp_P_CNCL_CNFM_RSLT_BY_OPR_SVR", new object[] {
                        pvStrGlobalCollection,
                        I1_b_plant_plant_cd,
                        dataSet}, this.cPCnclCnfmRsltByOp_P_CNCL_CNFM_RSLT_BY_OPR_SVROperationCompleted, userState);
        }
        
        private void OncPCnclCnfmRsltByOp_P_CNCL_CNFM_RSLT_BY_OPR_SVROperationCompleted(object arg) {
            if ((this.cPCnclCnfmRsltByOp_P_CNCL_CNFM_RSLT_BY_OPR_SVRCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cPCnclCnfmRsltByOp_P_CNCL_CNFM_RSLT_BY_OPR_SVRCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    // 이 유형 정의는 System.Data.Design.TypedDataSetSchemaImporterExtension 스키마 가져오기 확장에 의해 생성되었습니다.
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("DsPCnclCnfmRsltByOprSvr")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    public partial class DsPCnclCnfmRsltByOprSvr : global::System.Data.DataSet {
        
        private IG_P_PRODUCTION_RESULTSDataTable tableIG_P_PRODUCTION_RESULTS;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public DsPCnclCnfmRsltByOprSvr() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected DsPCnclCnfmRsltByOprSvr(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["IG_P_PRODUCTION_RESULTS"] != null)) {
                    base.Tables.Add(new IG_P_PRODUCTION_RESULTSDataTable(ds.Tables["IG_P_PRODUCTION_RESULTS"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public IG_P_PRODUCTION_RESULTSDataTable IG_P_PRODUCTION_RESULTS {
            get {
                return this.tableIG_P_PRODUCTION_RESULTS;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            DsPCnclCnfmRsltByOprSvr cln = ((DsPCnclCnfmRsltByOprSvr)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["IG_P_PRODUCTION_RESULTS"] != null)) {
                    base.Tables.Add(new IG_P_PRODUCTION_RESULTSDataTable(ds.Tables["IG_P_PRODUCTION_RESULTS"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableIG_P_PRODUCTION_RESULTS = ((IG_P_PRODUCTION_RESULTSDataTable)(base.Tables["IG_P_PRODUCTION_RESULTS"]));
            if ((initTable == true)) {
                if ((this.tableIG_P_PRODUCTION_RESULTS != null)) {
                    this.tableIG_P_PRODUCTION_RESULTS.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private void InitClass() {
            this.DataSetName = "DsPCnclCnfmRsltByOprSvr";
            this.Prefix = "";
            this.Namespace = "http://bizentro.com/DsPCnclCnfmRsltByOprSvr.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableIG_P_PRODUCTION_RESULTS = new IG_P_PRODUCTION_RESULTSDataTable();
            base.Tables.Add(this.tableIG_P_PRODUCTION_RESULTS);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private bool ShouldSerializeIG_P_PRODUCTION_RESULTS() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            DsPCnclCnfmRsltByOprSvr ds = new DsPCnclCnfmRsltByOprSvr();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public delegate void IG_P_PRODUCTION_RESULTSRowChangeEventHandler(object sender, IG_P_PRODUCTION_RESULTSRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class IG_P_PRODUCTION_RESULTSDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnprodt_order_no;
            
            private global::System.Data.DataColumn columnopr_no;
            
            private global::System.Data.DataColumn columnseq;
            
            private global::System.Data.DataColumn columnreport_dt;
            
            private global::System.Data.DataColumn columnreport_type;
            
            private global::System.Data.DataColumn columnprod_qty_in_order_unit;
            
            private global::System.Data.DataColumn columnprod_qty_in_base_unit;
            
            private global::System.Data.DataColumn columnrcpt_item_document_no;
            
            private global::System.Data.DataColumn columnreason_cd;
            
            private global::System.Data.DataColumn columnflag;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public IG_P_PRODUCTION_RESULTSDataTable() {
                this.TableName = "IG_P_PRODUCTION_RESULTS";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal IG_P_PRODUCTION_RESULTSDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected IG_P_PRODUCTION_RESULTSDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn prodt_order_noColumn {
                get {
                    return this.columnprodt_order_no;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn opr_noColumn {
                get {
                    return this.columnopr_no;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn seqColumn {
                get {
                    return this.columnseq;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn report_dtColumn {
                get {
                    return this.columnreport_dt;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn report_typeColumn {
                get {
                    return this.columnreport_type;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn prod_qty_in_order_unitColumn {
                get {
                    return this.columnprod_qty_in_order_unit;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn prod_qty_in_base_unitColumn {
                get {
                    return this.columnprod_qty_in_base_unit;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn rcpt_item_document_noColumn {
                get {
                    return this.columnrcpt_item_document_no;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn reason_cdColumn {
                get {
                    return this.columnreason_cd;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn flagColumn {
                get {
                    return this.columnflag;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public IG_P_PRODUCTION_RESULTSRow this[int index] {
                get {
                    return ((IG_P_PRODUCTION_RESULTSRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event IG_P_PRODUCTION_RESULTSRowChangeEventHandler IG_P_PRODUCTION_RESULTSRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event IG_P_PRODUCTION_RESULTSRowChangeEventHandler IG_P_PRODUCTION_RESULTSRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event IG_P_PRODUCTION_RESULTSRowChangeEventHandler IG_P_PRODUCTION_RESULTSRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event IG_P_PRODUCTION_RESULTSRowChangeEventHandler IG_P_PRODUCTION_RESULTSRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void AddIG_P_PRODUCTION_RESULTSRow(IG_P_PRODUCTION_RESULTSRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public IG_P_PRODUCTION_RESULTSRow AddIG_P_PRODUCTION_RESULTSRow(string prodt_order_no, string opr_no, int seq, System.DateTime report_dt, string report_type, decimal prod_qty_in_order_unit, decimal prod_qty_in_base_unit, string rcpt_item_document_no, string reason_cd, string flag) {
                IG_P_PRODUCTION_RESULTSRow rowIG_P_PRODUCTION_RESULTSRow = ((IG_P_PRODUCTION_RESULTSRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        prodt_order_no,
                        opr_no,
                        seq,
                        report_dt,
                        report_type,
                        prod_qty_in_order_unit,
                        prod_qty_in_base_unit,
                        rcpt_item_document_no,
                        reason_cd,
                        flag};
                rowIG_P_PRODUCTION_RESULTSRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowIG_P_PRODUCTION_RESULTSRow);
                return rowIG_P_PRODUCTION_RESULTSRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                IG_P_PRODUCTION_RESULTSDataTable cln = ((IG_P_PRODUCTION_RESULTSDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new IG_P_PRODUCTION_RESULTSDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal void InitVars() {
                this.columnprodt_order_no = base.Columns["prodt_order_no"];
                this.columnopr_no = base.Columns["opr_no"];
                this.columnseq = base.Columns["seq"];
                this.columnreport_dt = base.Columns["report_dt"];
                this.columnreport_type = base.Columns["report_type"];
                this.columnprod_qty_in_order_unit = base.Columns["prod_qty_in_order_unit"];
                this.columnprod_qty_in_base_unit = base.Columns["prod_qty_in_base_unit"];
                this.columnrcpt_item_document_no = base.Columns["rcpt_item_document_no"];
                this.columnreason_cd = base.Columns["reason_cd"];
                this.columnflag = base.Columns["flag"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            private void InitClass() {
                this.columnprodt_order_no = new global::System.Data.DataColumn("prodt_order_no", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnprodt_order_no);
                this.columnopr_no = new global::System.Data.DataColumn("opr_no", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnopr_no);
                this.columnseq = new global::System.Data.DataColumn("seq", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnseq);
                this.columnreport_dt = new global::System.Data.DataColumn("report_dt", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnreport_dt);
                this.columnreport_type = new global::System.Data.DataColumn("report_type", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnreport_type);
                this.columnprod_qty_in_order_unit = new global::System.Data.DataColumn("prod_qty_in_order_unit", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnprod_qty_in_order_unit);
                this.columnprod_qty_in_base_unit = new global::System.Data.DataColumn("prod_qty_in_base_unit", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnprod_qty_in_base_unit);
                this.columnrcpt_item_document_no = new global::System.Data.DataColumn("rcpt_item_document_no", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnrcpt_item_document_no);
                this.columnreason_cd = new global::System.Data.DataColumn("reason_cd", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnreason_cd);
                this.columnflag = new global::System.Data.DataColumn("flag", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnflag);
                this.columnprodt_order_no.DefaultValue = ((string)(""));
                this.columnopr_no.DefaultValue = ((string)(""));
                this.columnseq.DefaultValue = ((int)(0));
                this.columnreport_dt.DateTimeMode = global::System.Data.DataSetDateTime.Unspecified;
                this.columnreport_type.DefaultValue = ((string)(""));
                this.columnprod_qty_in_order_unit.DefaultValue = ((decimal)(0m));
                this.columnprod_qty_in_base_unit.DefaultValue = ((decimal)(0m));
                this.columnrcpt_item_document_no.DefaultValue = ((string)(""));
                this.columnreason_cd.DefaultValue = ((string)(""));
                this.columnflag.DefaultValue = ((string)(""));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public IG_P_PRODUCTION_RESULTSRow NewIG_P_PRODUCTION_RESULTSRow() {
                return ((IG_P_PRODUCTION_RESULTSRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new IG_P_PRODUCTION_RESULTSRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(IG_P_PRODUCTION_RESULTSRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.IG_P_PRODUCTION_RESULTSRowChanged != null)) {
                    this.IG_P_PRODUCTION_RESULTSRowChanged(this, new IG_P_PRODUCTION_RESULTSRowChangeEvent(((IG_P_PRODUCTION_RESULTSRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.IG_P_PRODUCTION_RESULTSRowChanging != null)) {
                    this.IG_P_PRODUCTION_RESULTSRowChanging(this, new IG_P_PRODUCTION_RESULTSRowChangeEvent(((IG_P_PRODUCTION_RESULTSRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.IG_P_PRODUCTION_RESULTSRowDeleted != null)) {
                    this.IG_P_PRODUCTION_RESULTSRowDeleted(this, new IG_P_PRODUCTION_RESULTSRowChangeEvent(((IG_P_PRODUCTION_RESULTSRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.IG_P_PRODUCTION_RESULTSRowDeleting != null)) {
                    this.IG_P_PRODUCTION_RESULTSRowDeleting(this, new IG_P_PRODUCTION_RESULTSRowChangeEvent(((IG_P_PRODUCTION_RESULTSRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void RemoveIG_P_PRODUCTION_RESULTSRow(IG_P_PRODUCTION_RESULTSRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DsPCnclCnfmRsltByOprSvr ds = new DsPCnclCnfmRsltByOprSvr();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "IG_P_PRODUCTION_RESULTSDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class IG_P_PRODUCTION_RESULTSRow : global::System.Data.DataRow {
            
            private IG_P_PRODUCTION_RESULTSDataTable tableIG_P_PRODUCTION_RESULTS;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal IG_P_PRODUCTION_RESULTSRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableIG_P_PRODUCTION_RESULTS = ((IG_P_PRODUCTION_RESULTSDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string prodt_order_no {
                get {
                    try {
                        return ((string)(this[this.tableIG_P_PRODUCTION_RESULTS.prodt_order_noColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'IG_P_PRODUCTION_RESULTS\' 테이블의 \'prodt_order_no\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableIG_P_PRODUCTION_RESULTS.prodt_order_noColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string opr_no {
                get {
                    try {
                        return ((string)(this[this.tableIG_P_PRODUCTION_RESULTS.opr_noColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'IG_P_PRODUCTION_RESULTS\' 테이블의 \'opr_no\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableIG_P_PRODUCTION_RESULTS.opr_noColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public int seq {
                get {
                    try {
                        return ((int)(this[this.tableIG_P_PRODUCTION_RESULTS.seqColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'IG_P_PRODUCTION_RESULTS\' 테이블의 \'seq\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableIG_P_PRODUCTION_RESULTS.seqColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public System.DateTime report_dt {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableIG_P_PRODUCTION_RESULTS.report_dtColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'IG_P_PRODUCTION_RESULTS\' 테이블의 \'report_dt\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableIG_P_PRODUCTION_RESULTS.report_dtColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string report_type {
                get {
                    try {
                        return ((string)(this[this.tableIG_P_PRODUCTION_RESULTS.report_typeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'IG_P_PRODUCTION_RESULTS\' 테이블의 \'report_type\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableIG_P_PRODUCTION_RESULTS.report_typeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public decimal prod_qty_in_order_unit {
                get {
                    try {
                        return ((decimal)(this[this.tableIG_P_PRODUCTION_RESULTS.prod_qty_in_order_unitColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'IG_P_PRODUCTION_RESULTS\' 테이블의 \'prod_qty_in_order_unit\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableIG_P_PRODUCTION_RESULTS.prod_qty_in_order_unitColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public decimal prod_qty_in_base_unit {
                get {
                    try {
                        return ((decimal)(this[this.tableIG_P_PRODUCTION_RESULTS.prod_qty_in_base_unitColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'IG_P_PRODUCTION_RESULTS\' 테이블의 \'prod_qty_in_base_unit\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableIG_P_PRODUCTION_RESULTS.prod_qty_in_base_unitColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string rcpt_item_document_no {
                get {
                    try {
                        return ((string)(this[this.tableIG_P_PRODUCTION_RESULTS.rcpt_item_document_noColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'IG_P_PRODUCTION_RESULTS\' 테이블의 \'rcpt_item_document_no\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableIG_P_PRODUCTION_RESULTS.rcpt_item_document_noColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string reason_cd {
                get {
                    try {
                        return ((string)(this[this.tableIG_P_PRODUCTION_RESULTS.reason_cdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'IG_P_PRODUCTION_RESULTS\' 테이블의 \'reason_cd\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableIG_P_PRODUCTION_RESULTS.reason_cdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string flag {
                get {
                    try {
                        return ((string)(this[this.tableIG_P_PRODUCTION_RESULTS.flagColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("\'IG_P_PRODUCTION_RESULTS\' 테이블의 \'flag\' 열의 값이 DBNull입니다.", e);
                    }
                }
                set {
                    this[this.tableIG_P_PRODUCTION_RESULTS.flagColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isprodt_order_noNull() {
                return this.IsNull(this.tableIG_P_PRODUCTION_RESULTS.prodt_order_noColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setprodt_order_noNull() {
                this[this.tableIG_P_PRODUCTION_RESULTS.prodt_order_noColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isopr_noNull() {
                return this.IsNull(this.tableIG_P_PRODUCTION_RESULTS.opr_noColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setopr_noNull() {
                this[this.tableIG_P_PRODUCTION_RESULTS.opr_noColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsseqNull() {
                return this.IsNull(this.tableIG_P_PRODUCTION_RESULTS.seqColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetseqNull() {
                this[this.tableIG_P_PRODUCTION_RESULTS.seqColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isreport_dtNull() {
                return this.IsNull(this.tableIG_P_PRODUCTION_RESULTS.report_dtColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setreport_dtNull() {
                this[this.tableIG_P_PRODUCTION_RESULTS.report_dtColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isreport_typeNull() {
                return this.IsNull(this.tableIG_P_PRODUCTION_RESULTS.report_typeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setreport_typeNull() {
                this[this.tableIG_P_PRODUCTION_RESULTS.report_typeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isprod_qty_in_order_unitNull() {
                return this.IsNull(this.tableIG_P_PRODUCTION_RESULTS.prod_qty_in_order_unitColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setprod_qty_in_order_unitNull() {
                this[this.tableIG_P_PRODUCTION_RESULTS.prod_qty_in_order_unitColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isprod_qty_in_base_unitNull() {
                return this.IsNull(this.tableIG_P_PRODUCTION_RESULTS.prod_qty_in_base_unitColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setprod_qty_in_base_unitNull() {
                this[this.tableIG_P_PRODUCTION_RESULTS.prod_qty_in_base_unitColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isrcpt_item_document_noNull() {
                return this.IsNull(this.tableIG_P_PRODUCTION_RESULTS.rcpt_item_document_noColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setrcpt_item_document_noNull() {
                this[this.tableIG_P_PRODUCTION_RESULTS.rcpt_item_document_noColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Isreason_cdNull() {
                return this.IsNull(this.tableIG_P_PRODUCTION_RESULTS.reason_cdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void Setreason_cdNull() {
                this[this.tableIG_P_PRODUCTION_RESULTS.reason_cdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsflagNull() {
                return this.IsNull(this.tableIG_P_PRODUCTION_RESULTS.flagColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetflagNull() {
                this[this.tableIG_P_PRODUCTION_RESULTS.flagColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public class IG_P_PRODUCTION_RESULTSRowChangeEvent : global::System.EventArgs {
            
            private IG_P_PRODUCTION_RESULTSRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public IG_P_PRODUCTION_RESULTSRowChangeEvent(IG_P_PRODUCTION_RESULTSRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public IG_P_PRODUCTION_RESULTSRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void cPCnclCnfmRsltByOp_P_CNCL_CNFM_RSLT_BY_OPR_SVRCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591